name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: alpine:latest
            preinstall: apk add git curl
          - container: centos:latest
            preinstall: dnf -y --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos && dnf -y install git
          - container: ubuntu:latest
            preinstall: apt-get -y && apt-get -y install curl git

    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Preinstall
        run: ${{ matrix.preinstall }}

      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: docker-credential-ecr-login version
