name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
  push:
    paths-ignore:
      - "**.md"
      - LICENSE

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Test plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: docker-credential-ecr-login version
